### ISSUE TITLE
为什么tableView右滑返回时会下移

### ISSUE THREAD

**Issue by 542604974** [Rogue24/JPSuspensionEntrance#1]
为什么tableView右滑返回时会下移？不隐藏导航栏，而且返回按钮点击的话看到页面下移

**Comment by 542604974** [comment]
//- (BOOL)gestureRecognizerShouldBegin:(UIGestureRecognizer *)gestureRecognizer{
//    if (gestureRecognizer == self.navCtr.interactivePopGestureRecognizer ||
//        gestureRecognizer == self.popInteraction.edgeLeftPanGR) {
//        if (self.navCtr.viewControllers.count <= 1) {
//            return NO;
//        }
//        BOOL conformsToProtocol = [self.navCtr.viewControllers.lastObject conformsToProtocol:@protocol(JPSuspensionEntranceProtocol)];
//        if (gestureRecognizer == self.navCtr.interactivePopGestureRecognizer && conformsToProtocol) {
//            return NO;
//        }
//        if (gestureRecognizer == self.popInteraction.edgeLeftPanGR) {
//            if (!conformsToProtocol || (self.suspensionView.panGR.state == UIGestureRecognizerStateBegan || self.suspensionView.panGR.state == UIGestureRecognizerStateChanged) ) {
//                return NO;
//            }
//        }
//    }
//    if (gestureRecognizer == self.suspensionView.panGR) {
//        if (self.popInteraction.edgeLeftPanGR.state == UIGestureRecognizerStateBegan || self.popInteraction.edgeLeftPanGR.state == UIGestureRecognizerStateChanged) {
//            return NO;
//        }
//    }
//    return YES;
//}

**Comment by 542604974** [comment]
我发现是这个手势的问题

**Comment by Rogue24** [comment]
可以发一份demo来看看吗

发自我的 iPhone

在 2018年9月5日，上午10:24，542604974 <notifications@github.com<mailto:notifications@github.com>> 写道：


为什么tableView右滑返回时会下移？不隐藏导航栏，而且返回按钮点击的话看到页面下移

**Comment by 542604974** [comment]
我在你的demo上viewController加上tableView也没问题，奇怪了

**Comment by 542604974** [comment]
设置了   self.edgesForExtendedLayout = UIRectEdgeNone;就会出现这个问题了

**Comment by Rogue24** [comment]
已修复该问题 可以在cocoapods上update一下 或者去Github上下载最新版本~谢谢反馈
________________________________
发件人: 542604974 <notifications@github.com>
发送时间: 2018年9月5日 8:04
收件人: Rogue24/JPSuspensionEntrance
抄送: 健了个平; Comment
主题: Re: [Rogue24/JPSuspensionEntrance] 为什么tableView右滑返回时会下移 (#1)


设置了 self.edgesForExtendedLayout = UIRectEdgeNone;就会出现这个问题了

―
