### ISSUE TITLE
present的VC

### ISSUE THREAD

**Issue by xindizhiyin2014** [Rogue24/JPSuspensionEntrance#3]

**Comment by xindizhiyin2014** [comment]
你好，present的ViewController是否支持悬浮球效果呢

**Comment by Rogue24** [comment]
您好，暂不支持~不过思路差不多的，可以监听present动画结束的那一刻转浮窗即可！
________________________________
发件人: xindizhiyin2014 <notifications@github.com>
发送时间: 2019年4月16日 9:27
收件人: Rogue24/JPSuspensionEntrance
抄送: Subscribed
主题: Re: [Rogue24/JPSuspensionEntrance] present的VC (#3)


你好，present的ViewController是否支持悬浮球效果呢

―
